### PR TITLE
docs: fix samples broken link

### PR DESCRIPTION
**Pull request by QzLP2P**
Link was wrong

# Description

The link in samples.md was wrong

Fixes # (issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have added tests to cover my changes
-   [x] I have made corresponding changes to the documentation

### Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

### CODE REVIEW

**Review by joelfoliveira — APPROVED** [review]

**Comment by joelfoliveira** [comment]
Hi @QzLP2P ,

Thank you for your contribution. As per the [Contribuiting Guidelines](https://github.com/Farfetch/loadshedding/blob/main/CONTRIBUTING.md), can you please change the commit message to follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) guideline?

Maybe something like: `docs: fix samples broken link`

**Review by ruiqbarbosa — APPROVED** [review]

**Review by brmagadutra — APPROVED** [review]

**Review by simaoribeiro — APPROVED** [review]

**Comment by simaoribeiro** [comment]
Hi @QzLP2P , I noticed that you changed the PR title to the one suggested by @joelfoliveira . Can you also reword the commit title from `Update samples.md` to the `docs: fix samples broken link` to follow our guidelines? Thanks

**Comment by QzLP2P** [comment]
> Hi @QzLP2P ,
> 
> Thank you for your contribution. As per the [Contribuiting Guidelines](https://github.com/Farfetch/loadshedding/blob/main/CONTRIBUTING.md), can you please change the commit message to follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) guideline?
> 
> Maybe something like: `docs: fix samples broken link`

I tried from github.com but I can’t rewrite the commit message.
Tomorrow I Will clone the repo to do it

**Comment by QzLP2P** [comment]
I finally create a new one, more simple for me https://github.com/Farfetch/loadshedding/pull/13

**Pull request closed without merging**
